ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-noble"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME=/home/kasm-default-profile
ENV STARTUPDIR=/dockerstartup
ENV INST_SCRIPTS=$STARTUPDIR/install

WORKDIR $HOME

######### Customize Container Here ###########


COPY ./src/ubuntu/install/chrome $INST_SCRIPTS/chrome/
RUN bash $INST_SCRIPTS/chrome/install_chrome.sh  && rm -rf $INST_SCRIPTS/chrome/

COPY ./src/ubuntu/install/p11-kit $INST_SCRIPTS/p11-kit/
RUN bash $INST_SCRIPTS/p11-kit/install_p11-kit.sh  && rm -rf $INST_SCRIPTS/p11-kit/

COPY ./src/ubuntu/install/anythingllm $INST_SCRIPTS/anythingllm/
RUN bash $INST_SCRIPTS/anythingllm/install_anythingllm.sh  && rm -rf $INST_SCRIPTS/anythingllm/

COPY ./src/ubuntu/install/only_office $INST_SCRIPTS/only_office/
RUN bash $INST_SCRIPTS/only_office/install_only_office.sh  && rm -rf $INST_SCRIPTS/only_office/

######### End Customizations ###########

RUN $STARTUPDIR/set_user_permission.sh $HOME && \
    rm -f /etc/X11/xinit/Xclients && \
    chown 1000:0 $HOME && \
    mkdir -p /home/kasm-user && \
    chown 1000:0 /home/kasm-user

ENV HOME=/home/kasm-user
WORKDIR $HOME

USER 1000

