ARG BASE_TAG="develop"
ARG BASE_IMAGE="ubuntu-noble-nvidia"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME=/home/kasm-default-profile
ENV STARTUPDIR=/dockerstartup
ENV INST_SCRIPTS=$STARTUPDIR/install
ENV JAVA_VERSION="17-jre"
ENV REFINE_VERSION="3.9.3"
ARG VSCODE_EXTENSIONS="ms-toolsai.datawrangler"
WORKDIR $HOME

######### Customize Container Here ###########

COPY ./src/ubuntu/install/only_office $INST_SCRIPTS/only_office/
RUN bash $INST_SCRIPTS/only_office/install_only_office.sh  && rm -rf $INST_SCRIPTS/only_office/

COPY ./src/ubuntu/install/orange $INST_SCRIPTS/orange/
RUN bash $INST_SCRIPTS/orange/install_orange.sh  && rm -rf $INST_SCRIPTS/orange/

COPY ./src/ubuntu/install/temurin_java $INST_SCRIPTS/temurin_java/
RUN bash $INST_SCRIPTS/temurin_java/install_temurin_java.sh  && rm -rf $INST_SCRIPTS/temurin_java/

COPY ./src/ubuntu/install/refine $INST_SCRIPTS/refine/
RUN bash $INST_SCRIPTS/refine/install_refine.sh  && rm -rf $INST_SCRIPTS/refine/

COPY ./src/ubuntu/install/weka $INST_SCRIPTS/weka/
RUN bash $INST_SCRIPTS/weka/install_weka.sh  && rm -rf $INST_SCRIPTS/weka/

# We already have VS Code from base, install the extensions
COPY ./src/ubuntu/install/vs_code $INST_SCRIPTS/vs_code/
RUN bash $INST_SCRIPTS/vs_code/install_extensions.sh "$VSCODE_EXTENSIONS"  && rm -rf $INST_SCRIPTS/vs_code/

######### End Customizations ###########

RUN chown 1000:0 $HOME

ENV HOME=/home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000

