ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-noble"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ARG CUDA_TOOLKIT_VERSION="12-6"
ARG PYENV_GIT_TAG="v2.5.1"

ENV HOME=/home/kasm-default-profile
ENV STARTUPDIR=/dockerstartup
ENV INST_SCRIPTS=$STARTUPDIR/install
ENV CUDA_TOOLKIT_VERSION=${CUDA_TOOLKIT_VERSION}
ENV PYENV_GIT_TAG=${PYENV_GIT_TAG}
ENV NVIDIA_DRIVER_CAPABILITIES=all
#ENV no_proxy=localhost,127.0.0.0

WORKDIR $HOME

RUN [ ! -f "$STARTUPDIR/custom_startup.sh" ] && echo "#!/bin/bash" > $STARTUPDIR/custom_startup.sh && chmod +x $STARTUPDIR/custom_startup.sh

######### Customize Container Here ###########

COPY ./src/ubuntu/install/chrome $INST_SCRIPTS/chrome/
RUN bash $INST_SCRIPTS/chrome/install_chrome.sh  && rm -rf $INST_SCRIPTS/chrome/

COPY ./src/ubuntu/install/p11-kit $INST_SCRIPTS/p11-kit/
RUN bash $INST_SCRIPTS/p11-kit/install_p11-kit.sh  && rm -rf $INST_SCRIPTS/p11-kit/

COPY ./src/ubuntu/install/cuda $INST_SCRIPTS/cuda/
RUN bash $INST_SCRIPTS/cuda/install_cuda_toolkit.sh  && rm -rf $INST_SCRIPTS/cuda/

COPY ./src/ubuntu/install/easydiffusion $INST_SCRIPTS/easydiffusion/
RUN bash $INST_SCRIPTS/easydiffusion/install_easydiffusion.sh  && rm -rf $INST_SCRIPTS/easydiffusion/

# Allow trust updates
RUN echo "ALL ALL=NOPASSWD: /usr/sbin/update-ca-certificates" > /etc/sudoers.d/ca-certs

RUN echo "grep -q 'sudo update-ca-certificates' ~/.bashrc || sudo update-ca-certificates" >> $STARTUPDIR/custom_startup.sh
RUN echo "grep -q 'export NODE_EXTRA_CA_CERTS' ~/.bashrc || echo export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt >> ~/.bashrc" >> $STARTUPDIR/custom_startup.sh
RUN grep -q 'export REQUESTS_CA_BUNDLE' $HOME/.bashrc || echo export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt >> $HOME/.bashrc
RUN grep -q 'export PIP_CERT' $HOME/.bashrc || echo export PIP_CERT=/etc/ssl/certs/ca-certificates.crt >> $HOME/.bashrc

RUN echo "$STARTUPDIR/process_launch_form.sh" >> $STARTUPDIR/custom_startup.sh

COPY ./src/ubuntu/install/pyenv/end_custom_startup.sh $INST_SCRIPTS/
RUN cat "$INST_SCRIPTS/end_custom_startup.sh" >> $STARTUPDIR/custom_startup.sh && rm "$INST_SCRIPTS/end_custom_startup.sh"

######### End Customizations ###########
RUN chown 1000:0 $HOME

ENV HOME=/home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
